modLoader = "javafml"
loaderVersion = "[${forge_version},)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "realism"
version = "${version}"
displayName = "Create Realism"
authors = "Stacode"
description = '''
A mod changing the Trains in create to be more realistic
'''
logoFile = "icon.png"

[[dependencies.realism]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.realism]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.realism]]
modId="create"
mandatory=true
versionRange="${create_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.realism]]
modId="tramways"
mandatory=false
versionRange="[${tramways_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.realism]]
modId="architectury"
mandatory=true
versionRange="[${architectury_api_version},)"
ordering="NONE"
side="BOTH"
